### ISSUE TITLE
Blue highlight for menu not showing up 

### ISSUE THREAD

**Issue by elainekamlley** [18F/guides-template#34]
on https://pages.18f.gov/joining-18f/ theres an issue with the menu. I noticed that when there are highlighted lists like job descriptions or interview breakdowns, the blue highlight on the menu disappears. This makes it particularly difficult if you're looking at in on the phone. Any help in fixing this, I would be much obliged!

**Comment by mbland** [comment]
So to be more specific, https://pages.18f.gov/joining-18f/who-we-are-hiring/ exhibits this behavior. Weird.

@nickbristow Is this a common accessibility ailment you're familiar with?

**Comment by nickbristow** [comment]
@elainekamlley @mbland so this happens when the title of the page and the text of the link don't match. I know this is a pretty fragile system ATM. 

In this case, the title has a `?` and the text doesn't. 

The code to highlight is just part of the ruby template. 
`<li {% if page.title == link.text %}class="sidebar-nav-active"{% endif %}>`

**Comment by elainekamlley** [comment]
Thanks @nickbristow and @mbland! Got a PR to fix that up: https://github.com/18F/joining-18f/pull/44
